services:
  - type: web
    name: hotel-booking-app
    env: static
    buildCommand: cd hotel-booking-app && npm install && npm run build
    staticPublishPath: ./hotel-booking-app/dist/hotel-booking-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
